Fix custom commands with newer setuptools
Fix custom commands to handle additional arguments to the run() method.
This is needed with newer versions of setuptools since they've started
passing 'show_deprecation' kwarg in easy_install command, and this
resulted in the following error:

```
Traceback (most recent call last):
  File "/tmp/pytest-cov/./setup.py", line 86, in <module>
    setup(
  File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.9/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3.9/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run(show_deprecation=False)
TypeError: run() got an unexpected keyword argument 'show_deprecation'
```

While at it, future-proof all overriden commands to accept pass any
arguments through.